# Generated by Django 5.0.2 on 2024-02-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100, unique=True)),
                ('sex_ratio', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('health', models.CharField(max_length=50)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.animal')),
            ],
        ),
    ]
