# Generated by Django 5.0.2 on 2024-02-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualanimal',
            name='animal_type',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='IndividualAnimal',
        ),
    ]
