# Generated by Django 5.0.2 on 2024-02-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_remove_animal_sex_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='habitat_image',
            field=models.ImageField(blank=True, null=True, upload_to='habitat_images/'),
        ),
    ]
