# Generated by Django 5.0.2 on 2024-02-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_alter_habitat_habitat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='habitat_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
