# Generated by Django 5.0.2 on 2024-02-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0005_habitat_habitat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='habitat_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/static/img/habitat_img/'),
        ),
    ]
