# Generated by Django 5.0.2 on 2024-02-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0006_alter_habitat_habitat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='habitat_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/habitat_img/'),
        ),
    ]
