# Generated by Django 5.0.2 on 2024-02-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0007_alter_habitat_habitat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualanimal',
            name='habitat',
        ),
        migrations.AddField(
            model_name='animal',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreApp.habitat'),
        ),
    ]
