# Generated by Django 5.0.2 on 2024-02-25 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0008_remove_individualanimal_habitat_animal_habitat'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualanimal',
            name='habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='coreApp.habitat'),
        ),
    ]
